// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3DaMM8oquPm7uj9fjwqmpjQQR-QWR6A',
    appId: '1:461201929766:android:bb84f7268401f04a5a18e7',
    messagingSenderId: '461201929766',
    projectId: 'getme-2caa6',
    storageBucket: 'getme-2caa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4vcBFfBgVHEQWVMB8G2zRMxKwR5uR8U',
    appId: '1:461201929766:ios:31d034f637ad5b4d5a18e7',
    messagingSenderId: '461201929766',
    projectId: 'getme-2caa6',
    storageBucket: 'getme-2caa6.appspot.com',
    iosClientId: '461201929766-ib2ctrnba9ditimtr5sutghte1qr0a8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
